spring:
  jpa:
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH0_ISSUER_URI}
          audience: ${AUTH0_AUDIENCE}

logging:
  level:
    com.gamewatch: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG

rawg:
  api:
    key: ${RAWG_API_KEY:}
